# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_backer.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(445, 262)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #3b3b3b;\n"
"    color: #ffffff;\n"
"    border: 1px outset;\n"
"    \n"
"}")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(20, 140, 75, 75))
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"   background-color: #a04dff;\n"
"    color: #ffffff;\n"
"   \n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #bc85fa;\n"
"    color: #ffffff;\n"
"   }\n"
"\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 140, 75, 75))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #ff4f11;\n"
"    color: #ffffff;\n"
"   }\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color:  #ff8153;\n"
"    color: #ffffff;\n"
"    }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.toolButton_1 = QtWidgets.QToolButton(Dialog)
        self.toolButton_1.setGeometry(QtCore.QRect(20, 20, 25, 19))
        self.toolButton_1.setObjectName("toolButton_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_1.setGeometry(QtCore.QRect(60, 20, 341, 21))
        self.lineEdit_1.setStyleSheet("QLineEdit {\n"
"    background-color: #5c5b5b;\n"
"    color: #ffffff;\n"
"}")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.toolButton_2 = QtWidgets.QToolButton(Dialog)
        self.toolButton_2.setGeometry(QtCore.QRect(20, 50, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 50, 341, 21))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #5c5b5b;\n"
"    color: #ffffff;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 80, 415, 23))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    \n"
"     color: #ffffff;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_1.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_1.setText(_translate("Dialog", "START"))
        self.pushButton_2.setText(_translate("Dialog", "RESET"))
        self.toolButton_1.setText(_translate("Dialog", "..."))
        self.lineEdit_1.setPlaceholderText(_translate("Dialog", "C:\\ путь к исходной папке"))
        self.toolButton_2.setText(_translate("Dialog", "..."))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "C:\\ путь к конечной папке"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
